apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.65.100-192.168.65.200
