apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sqsx
  namespace: sit
spec:
  ingressClassName: nginx 
  rules:
  - host: hy.sqsx.com
    http:
      paths:
      #- path: /sqsx
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-sqsx-service
            port: 
              number: 80
